# Site settings
version: 4.3.2
locale: "en-US"
title: "James Hawkins"
title_seperator: "-"
subtitle: #site tagline
name: "James Hawkins"
description: This is my personal blog about coding. This site will be built with Jekyll, Bootstrap and GitHub Pages.
url: "https://jameshawkins.codes"
baseurl: "/"
repository: "jhawksno/james-hawkins-codes"
breadcrumbs: true

algolia:
  application_id: WL8CI117VO
  index_name: james_hawkins_codes

# Where things are
sass:
  sass_dir: _sass
  load_paths:
    - _sass/
    - vendor/bundle/ruby/2.7.0/gems/

# Handling Reading
include: [".htaccess", "_posts", "_pages"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]

keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false

# Outputting
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 5 # amount of posts to show
paginate_path: /page:num
timezone: null

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: default
