# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
# theme                   : power-maker-jekyll
# power_maker_skin        : "default", "dark", "light"

# Site settings
locale                    : "en-US"
title                     : "James Hawkins Codes"
title_seperator           : "-"
subtitle                  : #site tagline
name                      : "James Hawkins"
description               : This is my personal blog about coding. This site will be built with Jekyll, Bootstrap and GitHub Pages.
url                       : "https://jameshawkins.codes"
baseurl                   : "/" # the subpath of your site, e.g. /blog
repository                : "jhawksno/james-hawkins-codes"
logo                      : #path of logo image to display in header, e.g. "/assets/images/your-logo.png"
breadcrumbs               : true #disabled by default

# Site Author
author:
  name: "James"
  avatar: # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person."
  location: "Canada"
  email: james.hawkins@snolab.ca
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"

# Where things are
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output: true

# Reading Files
include:
  - .htaccess
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Power Maker /docs
  - /test # ignore Power Maker /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 5 # amount of posts to show
paginate_path: /page:num
timezone: null

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true