# Site settings
version: 4.3.2
locale: "en-US"
title: "James_Hawkins.Codes"
title_seperator: "-"
subtitle: #site tagline
name: "James Hawkins"
description: This is my personal blog about coding. This site will be built with Jekyll, Bootstrap and GitHub Pages.
url: "https://jameshawkins.codes"
baseurl: "/" # the subpath of your site, e.g. /blog
repository: "jhawksno/james-hawkins-codes"
logo: #path of logo image to display in header, e.g. "/assets/images/your-logo.png"
breadcrumbs: true

# Where things are
destination: ./_site
collections_dir: .
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: _sass
  style: compressed
collections:
  posts:
    output: true

# Handling Reading
safe: false
include: [".htaccess", "_posts"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false

# Outputting
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 5 # amount of posts to show
paginate_path: /page:num
timezone: null

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # Posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
